### ISSUE TITLE
How to change icons?

### ISSUE THREAD

**Issue by medmo7** [fernando-silva-dev/react-native-switch-with-icons#1]
Thanks for this lib.

I don't see how to add custom, icons to the switch.

it seems that the path of icons is hardcoded in the lib, I'm right?

```
import ic_switch_on from '../../img/SwitchOn.png';
import ic_switch_off from '../../img/SwitchOff.png';
```

**Comment by Hadenaut** [comment]
Hello.
Those you see hardcoded are the defaults, to add your own icons you need to pass them as the `icon` prop.

Ex:
```
<SwitchWithIcons icon={{
  true: icon1, //This is the icon that is displayed in the thumb when the value is true
  false: icon2 //This is the icon that is displayed in the thumb when the value is false
}}/>
```
Hope that helps.
